### ISSUE TITLE
已经有人开始这么做了，你怎么看？

### ISSUE THREAD

**Issue by tusenpo** [picasso250/mofa#5]
![](https://cloud.githubusercontent.com/assets/20261845/16543366/b94bfe98-4103-11e6-8c27-81046d7db140.png)

![](https://cloud.githubusercontent.com/assets/20261845/16543368/b9c7e986-4103-11e6-9489-23c934bf8c47.png)

![](https://cloud.githubusercontent.com/assets/20261845/16543367/b9c4961e-4103-11e6-90c0-4238b52c7262.png)

**Comment by picasso250** [comment]
一颗赛艇！

**Comment by tusenpo** [comment]
我想请你念诗，做匿名图片分享社区

**Comment by cgoxopx** [comment]
吼哇
